Android/live data convenience
MapsIndoors/docs pull request #28
Opened 2021-01-12 14:55 UTC by timMikkelsen

2021-01-13 14:20 UTC, marksdk requested changes
@timMikkelsen Don't worry about the number of suggestions here; most of them are suggestions for commas, MapsIndoors terms that needs to start with an uppercase character  or the like.

This is very nice work, and I'm excited about seeing it live 👏

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/index.md
> +Here are examples of using the different methods to render live data on your map:
```suggestion
Here are examples of using the different methods to render Live Data on your map:
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/index.md
> +        <h3>java</h3>
@timMikkelsen `java` lowercase or `Java`?

```suggestion
        <h3>Java</h3>
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/index.md
> +        <h3>kotlin</h3>
@timMikkelsen Same here; lowercase or uppercase?

```suggestion
        <h3>Kotlin</h3>
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/index.md
> +        <h3>java</h3>
```suggestion
        <h3>Java</h3>
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/index.md
> +        <h3>kotlin</h3>
```suggestion
        <h3>Kotlin</h3>
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/index.md
> +Note that since there is no guarantee of what Live Data you receive first and Locations can have multiple Live Data updates on different domains. It can be advised to check the lastModifiedTimeStamp
```suggestion
Note that since there is no guarantee of which Live Data you receive first, and Locations can have multiple Live Data updates on different domains, we recommend checking the `lastModifiedTimeStamp` of each Live Data update to select which one to render.
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/index.md
> +        <h3>java</h3>
```suggestion
        <h3>Java</h3>
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/index.md
> +        <h3>kotlin</h3>
```suggestion
        <h3>Kotlin</h3>
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/index.md
> +        <h3>java</h3>
```suggestion
        <h3>Java</h3>
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/index.md
> +        <h3>kotlin</h3>
```suggestion
        <h3>Kotlin</h3>
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +In this tutorial you will learn to work with Live Updates / real-time data in MapsIndoors. It is recommended that you read the [Live Data Introduction](/android/v3/live-data) before continuing.
```suggestion
In this tutorial you will learn to work with Live Updates / real-time data in MapsIndoors. It is recommended that you read the [Live Data Introduction](/android/v3/live-data/) before continuing.
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +We will create a simple activity displaying a map that shows some dynamic changes that are initiated from Live Data sources known by MapsIndoors. If you do not have a Live Data integration in place f
```suggestion
We will create a simple activity displaying a map showing dynamic changes initiated from Live Data sources known by MapsIndoors. If you do not have a Live Data integration in place for your MapsIndoors project, you can use API key `2ae7d137162642618b5ce555` for demo and test purposes. The test data are of the Occupancy Domain Type and the Position Domain Type.
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +Start by creating an activity that has a google map view and a mapcontrol initiated.
```suggestion
Start by creating an activity that has a Google Maps map view and a `MapControl` initiated.
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +Add buttons to the view for toggling subscriptions, one button for Live Position Updates and one for Live Occupancy Updates.
```suggestion
Add buttons to the view for toggling subscriptions, one button for Live Position Updates, and one for Live Occupancy Updates.
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +Add a method `setupSubscriptionButtons()` setting up buttons that enables/disables the subscriptions. This example uses the convenience interface to setup live data for the app.
```suggestion
Add a method `setupSubscriptionButtons()` setting up buttons that enable/disable the subscriptions. This example uses the convenience interface to setup Live Data for the app.
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +        <h3>java</h3>
```suggestion
        <h3>Java</h3>
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +        <h3>kotlin</h3>
```suggestion
        <h3>Kotlin</h3>
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +If you are using the demo solution. You will need to allign the camera with one of the solutions venues. You can use this example to find a venue and position the camera on it.
```suggestion
If you are using the Demo Solution, you will need to align the camera with one of the Solution's Venues. You can use this example to find a Venue and position the camera on it.
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +        <h3>java</h3>
```suggestion
        <h3>Java</h3>
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +        <h3>kotlin</h3>
```suggestion
        <h3>Kotlin</h3>
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +Thats it you now have live data running on your app. If you need to show live data in another way, you can add handlers for this. Read more about this here [Rendering Live Data Locations](/android/v3
```suggestion
And that's it! You now have Live Data running on your app. If you need to show Live Data in another way, you can add handlers for it. Read more about this in [Rendering Live Data Locations](/android/v3/live-data/).
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +## Using livedata without the convenience interface
```suggestion
## Using Live Data without the "convenience interface"
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +If you need a different way of handling live data subscriptions completely, because of the limitations of the convenience interface. It is also possible to implement your own way of setting up subscr
```suggestion
If you need a different way of handling Live Data subscriptions completely, because of the limitations of the "convenience interface", it is also possible to implement your own way of setting up subscriptions and dealing with the responses.
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +Say you only need it for a few specific locations with positioning updates. You use thoose locations id to create a `LiveTopicCriteria` with the builder supplied on the class that matches what you wa
```suggestion
Say you only need it for a few specific Locations with positioning updates. You use those Location's IDs to create a `LiveTopicCriteria` with the builder supplied on the class that matches what you want. Once you have created the `LiveTopicCriteria`, you can subscribe to it through the `LiveDataManager`.
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +        <h3>java</h3>
```suggestion
        <h3>Java</h3>
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +        <h3>kotlin</h3>
```suggestion
        <h3>Kotlin</h3>
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +Once subscribed the location will update its position according to the live data it receives. If you want to disable the subscription later on you can store the `LiveTopicCriteria` and unsubscribe th
```suggestion
Once subscribed, the Location will update its position according to the Live Data it receives. If you want to disable the subscription later on, you can store the `LiveTopicCriteria`, and unsubscribe through `LiveDataManager.unsubscribeTopic(LiveTopicCritera liveTopicCriteria)`. The lifecycle of the subscription is already handled so there is no need to unsubscribe and resubscribe on Android lifecycles.
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +If you want to see the position update happening you can set up a listener through the `LiveDataManager` like in this example.
```suggestion
If you want to see the position update happening, you can set up a listener through the `LiveDataManager` like in this example.
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +        <h3>java</h3>
```suggestion
        <h3>Java</h3>
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +        <h3>kotlin</h3>
```suggestion
        <h3>Kotlin</h3>
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +This is quite a simple implementation to get live data up and running and see it working. Say you want to get the occupancy of your locations and have the label update to reflect how many people are
```suggestion
This is a really simple implementation to get Live Data up and running. 

Now let's say you want to get the Occupancy of your Locations and make the label update to reflect how many people are inside a room.
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +First we will implement a way to setup `LiveTopics` so we dont get too much data at once. Here we will create a `LiveTopicCriteria` that uses the currently viewed building together with listening on
```suggestion
First we will implement a way to setup `LiveTopics` so we don't get too much data at once. Here we will create a `LiveTopicCriteria` that uses the currently viewed Building together with listening on Occupancy updates. We will assign the `LiveTopicCriteria` to a variable so that we can unsubscribe when changing to another topic.
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +        <h3>java</h3>
```suggestion
        <h3>Java</h3>
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +        <h3>kotlin</h3>
```suggestion
        <h3>Kotlin</h3>
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +Now if you already have the live update listener from the previous position example, you can remove the positioning part on a specific location and instead implement a more generic way of handling th
```suggestion
Now if you already have the live update listener from the previous Position example, you can remove the Positioning part on a specific Location, and instead implement a more generic way of handling the new updates we subscribe to. Here is an example that updates the label with the amount of people in each room.
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +        <h3>java</h3>
```suggestion
        <h3>Java</h3>
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +        <h3>kotlin</h3>
```suggestion
        <h3>Kotlin</h3>
```

2021-01-13 14:20 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +You should now be able to hover between buildings and see labels being updated with the live data you have requested.
```suggestion
You should now be able to move between Buildings and see labels being updated with the Live Data you have requested.
```

2021-01-14 12:29 UTC, marksdk approved these changes

2021-01-14 12:32 UTC, marksdk requested changes

2021-01-14 12:32 UTC, marksdk commented on src/android/v3/live-data/live-data-tutorial.md
> +This is a really simple implementation to get Live Data up and running.
```suggestion
This is a really simple implementation to get Live Data up and running.
```

2021-01-14 13:53 UTC, Daniel-Nielsen approved these changes
Looks good!

2021-01-14 14:21 UTC, marksdk approved these changes

2021-01-15 08:19 UTC, merged