Update documentation for Kiosk app
MapsIndoors/docs pull request #465
Opened 2021-02-02 12:44 UTC by marksdk

2021-02-03 11:04 UTC, simonlaustsen commented on src/various/kiosk.md
>  * **`&timeout=20`** is the timeout period before resetting
Could we somehow state that this value is in seconds?

2021-02-03 11:10 UTC, simonlaustsen commented on src/various/kiosk.md
> -Moreover, MapsPeople needs to set `phoneCountryCode` in the Solution's `appConfig` like so:
This is still valid, but I'm not sure if it belongs here or somewhere else?

2021-02-03 11:11 UTC, simonlaustsen commented on src/various/kiosk.md
> +To collect statistics in Google Analytics, provide your MapsIndoors representative with a Google Analytics Property ID (tracking id). This can be set in the app config on a per-Solution basis.
_"This can be set **in the app config** on a per-Solution basis."_ 
Correct, but maybe not relevant information for customers? 🤔

2021-02-03 11:14 UTC, simonlaustsen commented on src/various/kiosk.md
> +Available Domain types can be found here: <https://app.mapsindoors.com/mapsindoors/js/sdk/latest/docs/mapsindoors.LiveDataManager.html#.LiveDataManager.LiveDataDomainTypes>
Can we add something about the customer should contact us if they are interested in live-data?

2021-02-03 11:16 UTC, simonlaustsen commented on src/various/kiosk.md
> +The `timeout` URL parameter is used to set a period after which the Kiosk will reset to its initial state if it has not been touched. The entered value is in seconds.
The timeout parameters are also mentioned above in:
_### `timeout` aka. "Reset kiosk"_

2021-02-03 11:19 UTC, simonlaustsen requested changes
Some minor comments :) 

Can I somehow see it without running it locally?

2021-02-03 11:41 UTC, marksdk commented on src/various/kiosk.md
>  * **`&timeout=20`** is the timeout period before resetting
```suggestion
* **`&timeout=20`** is the timeout period (in seconds) before resetting
```

2021-02-03 11:43 UTC, marksdk commented on src/various/kiosk.md
> -Moreover, MapsPeople needs to set `phoneCountryCode` in the Solution's `appConfig` like so:
@simonlaustsen It's listed in our internal documentation (I had the same thought as you 😉).

2021-02-03 11:45 UTC, marksdk commented on src/various/kiosk.md
> +The `liveData` URL parameter is saved in the browser's local storage as  `MIKIOSK:{miApiKey}-paramLiveData`.
```suggestion
The `liveData` URL parameter is saved in the browser's local storage as  `MIKIOSK:{miApiKey}-paramLiveData`.

[Get in touch](https://mapspeople.com/) to hear more about how to set up Live Data integrations for your Solution.
```

2021-02-03 11:46 UTC, marksdk commented on src/various/kiosk.md
> +Available Domain types can be found here: <https://app.mapsindoors.com/mapsindoors/js/sdk/latest/docs/mapsindoors.LiveDataManager.html#.LiveDataManager.LiveDataDomainTypes>
Good idea. Added a note about it a bit further down.

2021-02-03 11:48 UTC, marksdk commented on src/various/kiosk.md
> +The `timeout` URL parameter is used to set a period after which the Kiosk will reset to its initial state if it has not been touched. The entered value is in seconds.
Good catch 👍

2021-02-03 11:48 UTC, marksdk commented on src/various/kiosk.md
> +To collect statistics in Google Analytics, provide your MapsIndoors representative with a Google Analytics Property ID (tracking id). This can be set in the app config on a per-Solution basis.
```suggestion
To collect statistics in Google Analytics, provide your MapsIndoors representative with a Google Analytics Property ID (tracking id).
```

2021-02-03 11:49 UTC, marksdk commented on src/various/kiosk.md
> +To collect statistics in Google Analytics, provide your MapsIndoors representative with a Google Analytics Property ID (tracking id). This can be set in the app config on a per-Solution basis.
Good point. Removed.

2021-02-03 11:50 UTC, marksdk commented
Thanks for the review @simonlaustsen!

> Can I somehow see it without running it locally?

Unfortunately, no. But it's really easy to follow the guide in the README 😉

2021-02-05 08:57 UTC, simonlaustsen approved these changes
👍

2021-02-05 21:59 UTC, merged