Feature/timi/android getting started
MapsIndoors/docs pull request #593
Opened 2021-03-11 10:15 UTC by timMikkelsen

2021-03-15 10:45 UTC, marksdk requested changes

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/directions.md
> +After having created our list of search results we have a good starting point to creating directions between two locations.
```suggestion
After having created our list of search results, we have a good starting point for creating directions between two Locations.
```

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/directions.md
> +Since our search only supports a single search we will hardcode a location coordinate into our app and use that as the basis for our origin, we'll then create a route and navigate to a view of the th
```suggestion
Since our search only supports a single search, we will hardcode a Location's coordinate into our app, and use that as the basis for our Origin. Then we'll create a route, navigate to a view of the navigation details, and show a route on the map from the Origin to the Destination.
```

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/directions.md
> +Create a `Point` with the coordinates from the oval office on your MapsActivity.
```suggestion
Create a `Point` with the coordinates from the Oval Office Location on your MapsActivity.
```

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/directions.md
> +Now we will make a method that can generate a route for us with just a location (picked through the search list).
```suggestion
Now we will make a method that can generate a route for us with just a Location (picked from the search list).
```

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/directions.md
> +implement the `onRouteResult` method and make the method to generate a route. To generate a route you use `MPRoutingProvider` to query a route with 2 points. We already have a hardcoded starting loca
@timMikkelsen This paragraph is a bit hard to follow. Could try looking at it again?

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/directions.md
> +So we start by creating an onClickListener on our search `ViewHolder` inside the `SearchItemAdapter` on `onBindViewHolder` that calls a `createRoute` on our activity, to generate a route with the `MP
```suggestion
To generate a route with the `MPLocation`, we start by creating an `onClickListener` on our search `ViewHolder` inside the `SearchItemAdapter` on `onBindViewHolder`. This calls a `createRoute` on our activity and the route is generated.
```

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/directions.md
> +So we start by creating an onClickListener on our search `ViewHolder` inside the `SearchItemAdapter` on `onBindViewHolder` that calls a `createRoute` on our activity, to generate a route with the `MP
Is the above suggestion still correct code-wise?

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/directions.md
> +We create global variables of the `MPdirectionsRenderer` and `MPRoutingProvider` and create getter to the `MPDirectionsRenderer`to access it from fragments later on.
```suggestion

We create global variables of the `MPdirectionsRenderer` and `MPRoutingProvider` and create a getter to the `MPDirectionsRenderer` to access it from _fragments_ later on.
```

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/directions.md
> +  * @param route the route model used to render a navigation view.
```suggestion
  * `@param route` the route model used to render a navigation view.
```

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/directions.md
> +  * @param miError an MIError if anything goes wrong when generating a route
```suggestion
  * `@param miError` an `MIError` if anything goes wrong when generating a route
```

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/directions.md
> +  * @param miError an MIError if anything goes wrong when generating a route
Should `miError` and `MIError` be the same casing?

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/directions.md
> +Now we will create a fragment we can put into our BottomSheet to show the steps for each route and the time and distance it takes to travel the route.
```suggestion
Now we will create a fragment we can put into our BottomSheet and show the steps for each route, as well as the time and distance it takes to travel the route.
```

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/directions.md
> +Here we will use a viewpager to allow the user to switch between each step and a close button. To be able to remove the route and the bottomsheet from the activity.
```suggestion

Here we'll use a `viewpager` to allow the user to switch between each step, as well as display a "close" button so we are able to remove the route and the bottom sheet from the activity.
```

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/directions.md
> +Create the Navigation `Fragment` with a `FragmentStateAdapter` for the `ViewPager`
```suggestion
Create the Navigation `Fragment` with a `FragmentStateAdapter` for the `ViewPager`:
```

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/directions.md
> +Create the `RouteLegFragment` for the `ViewPager`
```suggestion
Create the `RouteLegFragment` for the `ViewPager`:
```

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/directions.md
> +To swap travel modes you just set the travel mode before making a query for the route.
```suggestion
To swap Travel Modes you set the Travel Mode before making a query for the route:
```

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/map.md
> +You will receive a unique API key to use when access has been granted. If you are exploring how this service can become part of your own product, you can read about [partnering with MapsPeople here](
@timMikkelsen Aren't these instructions in the shared files @simonlaustsen's made?

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/map.md
> +Place the following initialization code in the `onCreate` method in the activity that should display the Google map also assign the mapFragment view to a variable as we will use this later to initial
```suggestion
Place the following initialization code in the `onCreate` method in the activity that should display the Google map. You should also assign the `mapFragment` view to a variable as we will use this later to initialize `MapControl`:
```

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/map.md
> +In your `onMapReady` callback function, use the `MapControl` class to set up a Google map with MapsIndoors venues, buildings & locations:
```suggestion
In your `onMapReady` callback function, use the `MapControl` class to set up a Google map with MapsIndoors Venues, Buildings and Locations:
```

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/new-project.md
> +You can also follow the steps below to start your app from scratch or to enhance the Basic Examples, more features will be explained in the [guides](/android/v3/guides/).
```suggestion

You can also follow the steps below to start your app from scratch or to enhance the Basic Examples, more features will be explained in the [guides](/android/v3/guides/).
```

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/new-project.md
> +If you dont already have a project. We recommend using the Google Maps Activity preset from android studio to getting started on developing your MapsIndoors solution.
```suggestion
If you don't already have a project, we recommend using the Google Maps Activity preset from Android Studio to getting started on developing your MapsIndoors project.
```

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/new-project.md
> +Add the MapsIndoors SDK as a dependency to your project. The AAR for the MapsIndoors SDK contains both Java classes, SDK resources and AndroidManifest.xml template which gets merged into your applica
```suggestion
Add the MapsIndoors SDK as a dependency to your project. The _AAR_ for the MapsIndoors SDK contains both Java classes, SDK resources and an `AndroidManifest.xml` template which gets merged into your application's `AndroidManifest.xml` during build process. Add or merge in the following to your app's build gradle file (usually called `build.gradle`).
```

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/new-project.md
> +MapsIndoors rely on Java 8 features, so you must add the following compile options, also in *android* section of your *build.gradle* file:
```suggestion
MapsIndoors relies on Java 8 features, so you must add the following compile options, also in *android* section of your *build.gradle* file:
```

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/prerequisites.md
> +If you need to work with MapsIndoors SDK behind a firewall, you might need to [white-list some IP-adresses](../../ip-whitelisting).
@timMikkelsen I made changes to this exact snippet in all other files across the repo. Is this a new addition? If so, it needs to align with these commits: https://github.com/MapsIndoors/docs/commit/c3f158cc55bb094d27230a10dfbcd2ac9171f067

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/search.md
> +Start by creating a new activity or fragment to facilitate searches on your application. Here we will be using a fragment to search and show search results on and using a bottom sheet to show the res
```suggestion
Start by creating a new activity or fragment to facilitate searches on your application. Here we will be using a fragment to search and show search results on, and using a bottom sheet to display the results. We also create a search input field on our main map activity for the user to input the text they want to search for.

```

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/search.md
> +Both UI component implementations can be found in the getting started app sample.
This should be a link

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/search.md
> +To perform a search you will need to have initiated `MapsIndoors`. This was shown in the previous section of the getting started tutorial how you do this.
This should be a link.

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/search.md
> +For advanced usage of the search functionality read the Search guide and tutorials connected to it.
This too 🙂

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/search.md
> +To start by being able to search. We need a text input field where a user can write what he wants to search for.
```suggestion
To be able to search we need a text input field where a user can write what they want to search for.

```

Never "he", always "they". It reads the same but is better.

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/search.md
> +Start by creating a Fragment with a view only consisting of a Recycler View.
```suggestion
To accompany this we'll create a fragment and a `BottomSheet` to handle the `searchFragment`.

Start by creating a fragment with a view-only consisting of a `RecyclerView`.
```

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/search.md
> +Create an RecyclerView adapter and the accompanying Viewholder
```suggestion
Create a `RecyclerView` adapter and the accompanying `Viewholder`:
```

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/search.md
> +Implement a BottomSheet to the bottom of your MapsActivity Layout. The root of the view should be a CoordinatorLayout. You can find the full xml layout on **Link to the github sample with the full vi
```suggestion
Implement a `BottomSheet` to the bottom of your `MapsActivity` layout. The root of the view should be a `CoordinatorLayout`. You can find the full xml layout on **Link to the github sample with the full view**
```

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/search.md
> +Now add the search fragment to the bottomSheet in the search query method on your MapsActivity.
```suggestion
Now add the search fragment to the `bottomSheet` in the search query method on your `MapsActivity`.
```

`bottomSheet` or `BottomSheet`? There are both versions in the text.

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/search.md
> +When getting a search result you might want to only show thoose search results on the map. You can do this through calling `displaySearchResults(List<MPLocation> locations)` on `MapControl`. This met
```suggestion
When getting a search result, you might want to only show those search results on the map. You can do this through calling `displaySearchResults(List<MPLocation> locations)` on `MapControl`. This method has different parameters to make it easier for you as a developer to fit your exact need in terms of animation and more. This can be read in the [JavaDoc of `MapControl`](https://instert-link-here.tim). 

The standard implementation animates the camera to fit all Locations on the map and show the info window of a Location, if it's a list of only one Location. 

When you are done showing the search results you can call `clearMap()` on `MapControl`.
```

I hope you find the Easter egg above or we'll have a 404 on our hands 😉

2021-03-15 10:45 UTC, marksdk commented on src/android/v3/getting-started/search.md
> +The accompanying ui and implementation of this search experience can be found in the getting started app sample. Found on github: TODO, CREATE GITHUB SAMPLE PAGE.
```suggestion
The accompanying UI and implementation of this search experience can be found in the getting started app sample. Found on github: TODO, CREATE GITHUB SAMPLE PAGE.
```

2021-03-15 10:57 UTC, timMikkelsen commented on src/android/v3/getting-started/directions.md
> +  * @param route the route model used to render a navigation view.
Should we mix markdown and code examples?

2021-03-15 10:57 UTC, timMikkelsen commented on src/android/v3/getting-started/directions.md
> +  * @param miError an MIError if anything goes wrong when generating a route
the lower case is the parameter name. Code syntax always have parameters starting with lower case.

2021-03-15 10:59 UTC, timMikkelsen commented on src/android/v3/getting-started/map.md
> +You will receive a unique API key to use when access has been granted. If you are exploring how this service can become part of your own product, you can read about [partnering with MapsPeople here](
There are some android specific mentions inside the text. But i'll take a look if i cant use the shared files Simon made.

2021-03-15 11:02 UTC, timMikkelsen commented on src/android/v3/getting-started/prerequisites.md
> +If you need to work with MapsIndoors SDK behind a firewall, you might need to [white-list some IP-adresses](../../ip-whitelisting).
This was probably added before i merged in, a newer version of the docs. I'll put in the new stuff!

2021-03-15 11:10 UTC, timMikkelsen commented on src/android/v3/getting-started/search.md
> +Now add the search fragment to the bottomSheet in the search query method on your MapsActivity.
Should be upper case.

2021-03-16 08:47 UTC, timMikkelsen commented on src/android/v3/getting-started/directions.md
> +implement the `onRouteResult` method and make the method to generate a route. To generate a route you use `MPRoutingProvider` to query a route with 2 points. We already have a hardcoded starting loca
Check the new one. I tried explaining it a bit better.

2021-03-16 09:45 UTC, marksdk commented on src/android/v3/getting-started/directions.md
> +  * @param route the route model used to render a navigation view.
Ah, no—didn't see this was inside a tab

2021-03-16 09:48 UTC, marksdk requested changes

2021-03-16 09:48 UTC, marksdk commented on src/android/v3/getting-started/directions.md
> +To generate a route with the `MPLocation`, we start by creating an `onClickListener` on our search `ViewHolder` inside the `SearchItemAdapter` on `onBindViewHolder`. This calls a `createRoute` on our
```suggestion
Implement the `onRouteResult` method, and create a method called `createRoute(MPLocation mpLocation)`. To generate a route use `MPRoutingProvider` with our hardcoded `mUserLocation` and a point from the `MPLocation`.

To generate a route with the `MPLocation`, we start by creating an `onClickListener` on our search `ViewHolder` inside the `SearchItemAdapter` on `onBindViewHolder`. This calls a `createRoute` on our activity and the route is generated.
```

@timMikkelsen Is what I wrote here still correct? It's still a bit hard to follow for me, but might be spot on for the real developers reading it, so take it as a suggestion only 🙂

2021-03-16 09:52 UTC, timMikkelsen commented on src/android/v3/getting-started/directions.md
> +To generate a route with the `MPLocation`, we start by creating an `onClickListener` on our search `ViewHolder` inside the `SearchItemAdapter` on `onBindViewHolder`. This calls a `createRoute` on our
The query bit is derived from actually being what the method on MPRouteProvider is called. Does it make sense if you read the examples below?

2021-03-16 12:43 UTC, timMikkelsen commented on src/android/v3/getting-started/new-project.md
> +MapsIndoors relies on Java 8 features, so you must add the following compile options, also in *android* section of your *build.gradle* file:
Yes, i am pretty sure it is. Our SDK uses a lot of java 8 features.

2021-03-16 12:44 UTC, timMikkelsen commented on src/android/v3/getting-started/map.md
> +## Setup Google Maps
You are correct on both. I'll remove them and update some things for earlier parts in the getting started guide. To tell the user about starting a project with all of the Google Maps parts already taking care of.

2021-03-16 13:19 UTC, Daniel-Nielsen commented on src/android/v3/getting-started/new-project.md
> +MapsIndoors relies on Java 8 features, so you must add the following compile options, also in *android* section of your *build.gradle* file:
Ok, I was just asking because I seem to recall it has been like this for quite some time...

2021-03-16 13:31 UTC, timMikkelsen commented on src/android/v3/getting-started/new-project.md
> +MapsIndoors relies on Java 8 features, so you must add the following compile options, also in *android* section of your *build.gradle* file:
Yearh, a guess would be that most modern applications use it anyway. It's features like lambda's that are removed if you dont use java 8 😬  
You can read about it here if you are interested: https://developer.android.com/studio/write/java8-support

2021-03-19 09:10 UTC, Daniel-Nielsen approved these changes

2021-03-24 11:28 UTC, marksdk commented on src/android/v3/getting-started/new-project.md
> +You can also follow the steps below to start your app from scratch or to enhance the Basic Examples, more features will be explained in the [guides](/android/v3/guides/).
```suggestion
You can also follow the steps below to start your app from scratch or to enhance the Basic Examples, more features will be explained in the [guides]({{ site.url }}/android/v3/guides/).
```

2021-03-24 11:30 UTC, marksdk commented on src/android/v3/guides/getting-started-on-directions.md
>  To get a Route result we must query the `MPRoutingProvider` with two `Point` objects. First, let's assume we have the latitude and longitude of a user. We create a `Point` object from the latitude an
```suggestion
To get a Route result we must query the `MPRoutingProvider` with two `Point` objects. First, let's assume we have the latitude and longitude of a user. We create a `Point` object from the latitude and longitude, and set the `zIndex` to `0` as the user is outside. We also need to find a Location the user should navigate to. This can be done by using the Marker the user has selected, and creating a UI function to generate a Route for the selected Location. In this example, we will query for a Location through an ID. We will also set the `TravelMode` to "Walking".
```

2021-03-24 11:32 UTC, marksdk approved these changes

2021-03-24 11:34 UTC, merged