Feature/android getting started live data
MapsIndoors/docs pull request #659
Opened 2021-06-23 12:27 UTC by timMikkelsen

2021-06-23 12:34 UTC, Daniel-Nielsen approved these changes

2021-06-23 13:42 UTC, marksdk commented on src/android/v3/getting-started/directions.md
> +See the full implementation of theese methods here: [MapsActivity.java](https://github.com/MapsIndoors/MapsIndoors-Getting-Started-Android/blob/master/app/src/main/java/com/example/mapsindoorsgetting
```suggestion
See the full implementation of these methods here: [MapsActivity.java](https://github.com/MapsIndoors/MapsIndoors-Getting-Started-Android/blob/master/app/src/main/java/com/example/mapsindoorsgettingstarted/MapsActivity.java#L218-L267) or [MapsActivity.kt](https://github.com/MapsIndoors/MapsIndoors-Getting-Started-Android-Kotlin/blob/main/app/src/main/java/com/example/mapsindoorsgettingstartedkotlin/MapsActivity.kt#L185-L225)
```

2021-06-23 13:47 UTC, marksdk requested changes

2021-06-23 13:47 UTC, marksdk commented on src/android/v3/getting-started/livedata.md
> +Enabling of Live Data through `MapControl` can be done as simple as calling `mapControl.enableLiveData()` with a [Domain Type](https://app.mapsindoors.com/mapsindoors/reference/android/v3/index.html)
```suggestion
Enabling Live Data through `MapControl` is as simple as calling `mapControl.enableLiveData()` with a [Domain Type](https://app.mapsindoors.com/mapsindoors/reference/android/v3/index.html).
```

Is this still correct, @timMikkelsen?

2021-06-23 13:47 UTC, marksdk commented on src/android/v3/getting-started/livedata.md
> +We will create a new method on our `MapsActivity` called `enableLiveData()` to enable live data for the solution.
```suggestion
We will create a new method on our `MapsActivity` called `enableLiveData()` to enable Live Data for the Solution.
```

2021-06-23 13:47 UTC, marksdk commented on src/android/v3/getting-started/livedata.md
> +    //Enabling live data for the three known live data domains that are enabled for this solution.
```suggestion
    //Enabling Live Data for the three known Live Data Domains enabled for this Solution.
```

2021-06-23 13:47 UTC, marksdk commented on src/android/v3/getting-started/livedata.md
> +    //Enabling live data for the three known live data domains that are enabled for this solution.
```suggestion
    //Enabling Live Data for the three known Live Data Domains enabled for this Solution.
```

2021-06-23 13:47 UTC, marksdk commented on src/android/v3/getting-started/livedata.md
> +By consequence, `MapControl` will manage the Live Data subscriptions needed for the current visible map and provide a default rendering of the Live Updates depending on the Domain Type.
```suggestion
By consequence, `MapControl` will manage the Live Data subscriptions needed for the currently visible map and provide a default rendering of the Live Data updates depending on the Domain Type.
```

2021-06-23 13:47 UTC, marksdk commented on src/android/v3/getting-started/livedata.md
> +In the context of your view controller showing a map, just add the call after creating your `MapControl` object used in the `Activity` in the `initMapControl()` method created earlier.
```suggestion
In the context of your view controller showing a map, add the call after creating your `MapControl` object used in the `Activity` in the `initMapControl()` method created earlier.
```

2021-06-23 13:47 UTC, marksdk commented on src/android/v3/getting-started/livedata.md
> +        //Enable live data on the map
```suggestion
        //Enable Live Data on the map
```

2021-06-23 13:47 UTC, marksdk commented on src/android/v3/getting-started/livedata.md
> +    //Enable live data on the map
```suggestion
    //Enable Live Data on the map
```

2021-06-23 13:47 UTC, marksdk commented on src/android/v3/getting-started/search.md
> +We then add an `EditorActionListener` and a `OnClickListener` to our text input field and our search button in the `onCreate` of `MapsActivity`. To call our search method with the text in the search
```suggestion
To call our search method with the text in the search input field, we then add an `EditorActionListener` and a `OnClickListener` to the text input field and the search button in the `onCreate` of `MapsActivity`. Find the full `onCreate` example here: [MapsActivity.java](https://github.com/MapsIndoors/MapsIndoors-Getting-Started-Android/blob/master/app/src/main/java/com/example/mapsindoorsgettingstarted/MapsActivity.java#L53-L117) or [MapsActivity.kt](https://github.com/MapsIndoors/MapsIndoors-Getting-started-android-Kotlin/blob/main/app/src/main/java/com/example/mapsindoorsgettingstartedkotlin/MapsActivity.kt#L42-L106)
```

2021-06-24 08:02 UTC, fhansenMP approved these changes

2021-06-24 10:44 UTC, marksdk commented on src/shared/getting-started/prerequisites/api-key-mapsindoors.md
> +If you are not a customer you can use this demo MapsIndoors API key `{{sdk.tutorialAPIKey}}` to follow this guide or you can [contact MapsPeople](https://resources.mapspeople.com/contact-us) to get y
```suggestion
If you are not a customer, you can use this demo MapsIndoors API key `{{sdk.tutorialAPIKey}}` to follow this guide, or you can [contact MapsPeople](https://resources.mapspeople.com/contact-us) to get your building drawings processed and hosted by us to receive a unique API key.
```

2021-06-24 10:44 UTC, marksdk approved these changes

2021-06-24 10:44 UTC, marksdk commented
Nice work @timMikkelsen 👏

2021-06-24 10:51 UTC, merged